---
- name: default
  hosts: molecule-takel-systemd

  roles:
    - takel-systemd

  post_tasks:
    - name: (converge) start services
      service:
        name: "{{ item.name }}"
        state: started
      loop: "{{ takel_systemd_service_list }}"
