---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint molecule/*/*.yml
  flake8
platforms:
  - name: molecule-takel-systemd
    image: takelage/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        takel_systemd_service_list:
          - name: takel_test_service01
            type: simple
            descripton: 'takel example01 service'
            wanted_by: network.target
            user: root
            group: root
            environment_file: example.env
            environment_file_vars:
              TAKEL_SYSTEMD_EXAMPLE: 'takel_example01_service'
            working_directory: /tmp
            exec_start: >-
              while true; do echo $TAKEL_SYSTEMD_EXAMPLE; sleep 2; done
          - name: takel_test_service02
            type: simple
            descripton: 'takel example02 service'
            wanted_by: network.target
            user: root
            group: root
            working_directory: /tmp
            exec_start: >-
              while true; do echo "hello $FOO"; sleep 2; done
            environment_vars:
              FOO: 'takel_example02_service'
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../system/test_*.py
  options:
    # p: cacheprovider
    s: true
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
