# frozen_string_literal: true

cmd_image_docker_base_debian10 = 'docker pull debian:buster-slim && ' \
    'mkdir -p packer/images/docker/base/debian10 && ' \
    'cd packer && packer build ' \
    "--var 'base_repo=debian' " \
    "--var 'base_tag=buster-slim' " \
    "--var 'target_user=#{@project['local_user']}' " \
    "--var 'target_repo=#{@project['dockerhub_base_tag']}' " \
    "--var 'target_tag=latest' " \
    'templates/docker/base/debian10/packer.json'

namespace :image do
  namespace :docker do
    namespace :base do
      desc 'Build Debian buster image with packer'
      task :debian10 do
        @commands << cmd_image_docker_base_debian10
      end
    end
  end
end
