---
takel_nginx_server_names:
  - pad
takel_nginx_site_name: "{{ project['name'] }}"

takel_nginx_site: |
  server {
    listen 80 default deferred;
    server_name _;

    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name _;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    ssl on;

    ssl_certificate {{ takel_nginx_ssl_cert }};
    ssl_certificate_key {{ takel_nginx_ssl_key }};

    ssl_session_timeout 5m;
    ssl_session_cache {{ takel_nginx_ssl_session_cache }};

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers {{ takel_nginx_ssl_ciphers | join(':') }};

    location = / {
        return 301 /etherpad;
    }

    location /etherpad {
      proxy_pass http://localhost:9001/;
      rewrite /etherpad/(.*) /$1 break;
      rewrite ^/etherpad$ /etherpad/ permanent;
      proxy_redirect / /etherpad/;
      proxy_set_header Host $host;
      proxy_pass_header Server;
      # be carefull, this line doesn't override any proxy_buffering on set in a conf.d/file.conf
      proxy_buffering off;
      proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
      proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
      proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
      proxy_set_header Host $host;  # pass the host header
      proxy_http_version 1.1;  # recommended with keepalive connections
      # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

    location /etherpad/socket.io {
      rewrite /etherpad/socket.io/(.*) /socket.io/$1 break;
      proxy_pass http://localhost:9001/;
      proxy_redirect / /etherpad/;
      proxy_set_header Host $host;
      proxy_buffering off;
      proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
      proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
      proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
      proxy_set_header Host $host;  # pass the host header
      proxy_http_version 1.1;  # recommended with keepalive connections
      # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

    location /static {
      rewrite /static/(.*) /static/$1 break;
      proxy_pass http://localhost:9001/;
      proxy_set_header Host $host;
      proxy_buffering off;
    }
  }

  # we're in the http context here
  map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
  }
