---
- name: (bin) create bin directory
  file:
    path: "{{ takel_etherpad_bin }}"
    state: directory
    owner: etherpad
    group: etherpad
    mode: 0755

- name: (bin) copy scripts
  template:
    src: "{{ item }}.j2.sh"
    dest: "{{ takel_etherpad_bin }}/{{ item }}"
    owner: etherpad
    group: etherpad
    mode: 0755
  loop:
    - etherpad-admin-password-dice
    - etherpad-admin-password-get
    - etherpad-admin-password-set
    - takelpad

- name: (bin) create symlink to takelpad script
  file:
    src: "{{ takel_etherpad_bin }}/takelpad"
    dest: /usr/local/bin/takelpad
    state: link
