---
- name: (configure) copy etherpad configuration
  template:
    src: etherpad-settings.j2.json
    dest: "{{ takel_etherpad_lib }}/settings.json"
    owner: etherpad
    group: etherpad
    mode: '0640'
  notify: restart etherpad
  tags:
    - molecule-idempotence-notest

- name: (configure) run installDeps.sh
  shell: ./installDeps.sh
  args:
    chdir: "{{ takel_etherpad_lib }}/src/bin"
  become: true
  become_user: etherpad
  tags:
    - molecule-idempotence-notest
