---
- name: (install) install packages
  ansible.builtin.apt:
    name: "{{ takel_etherpad_deb_install_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: (install) clone etherpad lite
  ansible.builtin.git:
    repo: "{{ takel_etherpad_repo }}"
    dest: "{{ takel_etherpad_lib }}"
    version: "{{ takel_etherpad_branch }}"
  become: true
  become_user: etherpad
