---
- name: (handler) reload daemon
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  listen: reload daemon

- name: (handler) enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    force: true
  listen: enable services
  loop: "{{ takel_systemd_handler_services_list }}"

- name: (handler) activate systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    force: true
  listen: activate systemd-networkd

- name: (handler) activate systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
    force: true
  listen: activate systemd-resolved
  notify: remove /etc/resolv.conf

- name: (handler) remove /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  listen: remove /etc/resolv.conf
  notify: create symlink /etc/resolv.conf

- name: (handler) create symlink /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    src: /run/systemd/resolve/stub-resolv.conf
    state: link
    force: true
  listen: create symlink /etc/resolv.conf
