# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Create and deploy prod image to dockerhub'
  task prod: %w[git:warn
                dockerhub:login
                rubylint
                images:project:molecule:lint
                takelscripts
                images:project:update
                images:project:build
                images:project:molecule:test
                git:tag
                dockerhub:project:tag
                dockerhub:project:push]
end
