# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Create and deploy base image to vagrantup'
  task base: %w[vagrantup:takelbase:base]

  desc 'Create and deploy project image to vagrantup'
  task project: %w[vagrantup:takelbase:project]
end
