# frozen_string_literal: true

require 'rake'

cmd_dockerhub_base_registry_login = 'docker login'

cmd_dockerhub_base_registry_push = 'docker push ' \
    "#{@project['dockerhub_base_user']}/#{@project['dockerhub_base_repo']}:" \
    "#{@project['dockerhub_base_tag']} && " \
    'docker push ' \
    "#{@project['dockerhub_base_user']}/#{@project['dockerhub_base_repo']}:" \
    'latest'

cmd_dockerhub_base_registry_tag = 'docker tag ' \
    "#{@project['local_user']}/#{@project['dockerhub_base_tag']} " \
    "#{@project['dockerhub_base_user']}/#{@project['dockerhub_base_repo']}:" \
    "#{@project['dockerhub_base_tag']} && " \
    'docker tag ' \
    "#{@project['local_user']}/#{@project['dockerhub_base_tag']} "\
    "#{@project['dockerhub_base_user']}/#{@project['dockerhub_base_repo']}:" \
    'latest'

namespace :dockerhub do
  namespace :takelbase do
    namespace :base do
      namespace :registry do
        desc 'Log in to hub.docker.com'
        task :login do
          @commands << cmd_dockerhub_base_registry_login
        end

        desc 'Push base image to hub.docker.com'
        task :push do
          @commands << cmd_dockerhub_base_registry_push
        end

        desc 'Tag base image for hub.docker.com'
        task :tag do
          @commands << cmd_dockerhub_base_registry_tag
        end
      end
    end
  end
end
