# frozen_string_literal: true

require 'rake'

namespace :vagrantup do
  desc 'Create and deploy base image to vagrantup'
  task base: %w[vagrantup:base:registry:login
                rubylint
                image:base:vbox:debian10
                vagrantup:base:registry:publish]
end
