---
name: takelage-pad
version: 0.7.10

local_user: packer_local

vboxes:
  project:
    base_user: takelwerk
    base_repo: takelbase
    target_user: takelwerk
    target_repo: takelpad
    ansible_playbook: "playbook-site.yml"

images:
  project:
    base_user: takelwerk
    base_repo: takelbase
    base_tag: latest
    target_user: takelwerk
    target_repo: takelpad
    command: /lib/systemd/systemd
    packer_command: /lib/systemd/systemd
    privileged: true
    layers:
      - site
