---
# project settings
project: takelage-pad
version: 0.1.0
local_user: packer_local

# dockerhub settings for the base image
dockerhub_base_user: takelage
dockerhub_base_repo: takelbase
dockerhub_base_tag: debian-buster

# dockerhub settings
dockerhub_prod_user: takelwerk
dockerhub_prod_repo: takelpad
