---
# project settings
project: takelage-pad
version: 0.5.1
local_user: packer_local

# dockerhub settings for the base image
dockerhub_base_user: takelage
dockerhub_base_repo: takelbase
dockerhub_base_tag: debian-buster

# vagrantup settings for the base image
vagrantup_base_user: takelwerk
vagrantup_base_repo: takelbase
vagrantup_base_version: 0.2.4

# dockerhub settings
dockerhub_prod_user: takelwerk
dockerhub_prod_repo: takelpad

# vagrantup settings
vagrantup_prod_user: takelwerk
vagrantup_prod_repo: takelpad
