Vagrant.configure(2) do |config|
  config.vm.box = "takelwerk/takelpad"
  config.vm.network :private_network, ip: '10.10.255.208'
  config.vm.network :public_network
  config.vm.define :takelpad
  config.vm.hostname = 'takelpad'
  config.vm.boot_timeout = 120
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'takelpad'
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
  end
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
