# frozen_string_literal: true

require 'rake'

cmd_vagrantup_takelbase_base_cloud_login = 'vagrant cloud auth login'

cmd_vagrantup_takelbase_base_cloud_publish = 'cd packer && ' \
    'vagrant cloud publish ' \
    "#{@project['vagrantup_base_user']}/#{@project['vagrantup_base_repo']} " \
    "#{@project['vagrantup_base_version']} " \
    'virtualbox ' \
    'images/vbox/takelbase/base/debian10/takelwerk-takelbase.box'

namespace :vagrantup do
  namespace :takelbase do
    namespace :base do
      namespace :cloud do
        desc 'Log in to app.vagrantup.com'
        task :login do
          @commands << cmd_vagrantup_takelbase_base_cloud_login
        end

        desc 'Publish base image at app.vagrantup.com'
        task :publish do
          @commands << cmd_vagrantup_takelbase_base_cloud_publish
        end
      end
    end
  end
end
