---
- name: prepare
  hosts: molecule-takel-nginx
  gather_facts: false
  roles:
    - takel_ssl
    - takel_nginx

- name: prepare
  hosts: molecule-takel-nginx-system
  gather_facts: false
  tasks:
    - name: (prepare) Install curl
      apt:
        name: curl
        update_cache: true
