---
- name: converge
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: attach molecule container to docker network
      docker_container:
        name: molecule-takel-nginx
        networks:
          - name: "{{ lookup('env','HOSTNAME') }}"
        networks_cli_compatible: false
        privileged: true
      delegate_to: 127.0.0.1

  roles:
    - takel_ssl
    - takel_nginx
