---
driver:
  name: docker
platforms:
  - name: molecule-takel-nginx
    image: takelwerk/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: systest
    networks:
      - name: systest
  - name: molecule-takel-nginx-system
    image: takelwerk/takelslim
    command: /usr/bin/tail -f /dev/null
    pre_build_image: true
    networks:
      - name: systest
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        takel_ssl_common_name: >-
          molecule_takel_nginx
        takel_ssl_subject_alt_name: >-
          molecule_takel_nginx.local
        takel_nginx_server_names:
          - molecule_takel_nginx
          - molecule_takel_nginx.local
verifier:
  name: testinfra
  options:
    s: true
  additional_files_or_dirs:
    - ../system/test_*.py
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
