---
- name: (install) install prerequisites
  apt:
    name: "{{ takel_nodejs_deb_install_prerequisites }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: (install) install nodesource repository
  shell: |
    set -o pipefail
    curl -sL {{ takel_nodejs_source_url }} | sudo -E bash -
  args:
    executable: /bin/bash
    creates: /etc/apt/sources.list.d/nodesource.list

- name: (install) install packages
  apt:
    name: "{{ takel_nodejs_deb_install_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
