# frozen_string_literal: true

require 'rake'

namespace :ansible do
  namespace :docker do
    namespace :takelbase do
      namespace :project do
        namespace :prod do |env|
          namespace :from_base do
            @list_ansible_docker_takelbase_project.each do |command|
              desc "Run molecule #{command} from base image " \
               "in #{env.scope.head} environment"
              task command do
                @commands << format(
                  @cmd_ansible_docker_takelbase_project,
                  command: command,
                  converge_playbook: 'playbook-project-base.yml',
                  image: 'takelage/takelbase',
                  project_environment: env.scope.head
                )
              end
            end
          end
        end
      end
    end
  end
end
