---
- name: (main) include preinstall
  ansible.builtin.import_tasks: preinstall.yml
  tags:
    - takel
    - takel_gopass
    - takel_gopass_preinstall

- name: (main) include docker repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - takel
    - takel_gopass
    - takel_gopass_repository

- name: (main) include install
  ansible.builtin.import_tasks: install.yml
  tags:
    - takel
    - takel_gopass
    - takel_gopass_install

- name: (main) include completion
  ansible.builtin.import_tasks: completion.yml
  tags:
    - takel
    - takel_gopass
    - takel_gopass_completion
