---
- name: reload daemon
  systemd:
    daemon_reload: true
    force: true

- name: enable services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    force: true
  loop: "{{ takel_systemd_handler_services_list }}"
