# frozen_string_literal: true

require 'rake'

cmd_dockerhub_prod_registry_login = 'docker login'

cmd_dockerhub_prod_registry_push = 'docker push ' \
    "#{@project['dockerhub_prod_user']}/#{@project['dockerhub_prod_repo']}:" \
    "#{@project['version']} && " \
    'docker push ' \
    "#{@project['dockerhub_prod_user']}/#{@project['dockerhub_prod_repo']}:" \
    'latest'

cmd_dockerhub_prod_registry_tag = 'docker tag ' \
    "#{@project['local_user']}/#{@project['name']}:prod " \
    "#{@project['dockerhub_prod_user']}/#{@project['dockerhub_prod_repo']}:" \
    "#{@project['version']} && " \
    'docker tag ' \
    "#{@project['local_user']}/#{@project['name']}:prod " \
    "#{@project['dockerhub_prod_user']}/#{@project['dockerhub_prod_repo']}:" \
    'latest'

namespace :dockerhub do
  namespace :takelbase do
    namespace :project do
      namespace :prod do
        namespace :registry do
          desc 'Log in to hub.docker.com'
          task :login do
            @commands << cmd_dockerhub_prod_registry_login
          end

          desc 'Push production image to hub.docker.com'
          task :push do
            @commands << cmd_dockerhub_prod_registry_push
          end

          desc 'Tag production image for hub.docker.com'
          task :tag do
            @commands << cmd_dockerhub_prod_registry_tag
          end
        end
      end
    end
  end
end
