---
- name: (main) include preinstall
  import_tasks: preinstall.yml
  tags:
    - takel
    - takel_nodejs
    - takel_nodejs_preinstall

- name: (main) include nodejs repository
  import_tasks: repository.yml
  tags:
    - takel
    - takel_nodejs
    - takel_nodejs_repository

- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_nodejs
    - takel_nodejs_install

- name: (main) include completion
  import_tasks: completion.yml
  tags:
    - takel
    - takel_nodejs
    - takel_nodejs_completion
