# frozen_string_literal: true

cmd_image_vbox_takelbase_base_debian10 = \
  'mkdir -p packer/images/vbox/takelbase/base/debian10 && ' \
  'cd packer && ' \
  'packer build templates/vbox/takelbase/base/debian10/packer.json'

namespace :image do
  namespace :vbox do
    namespace :takelbase do
      namespace :base do
        desc 'Build Debian buster image with packer'
        task :debian10 do
          @commands << cmd_image_vbox_takelbase_base_debian10
        end
      end
    end
  end
end
