# frozen_string_literal: true

require 'rake'

namespace :dockerhub do
  namespace :takelbase do
    desc 'Create and deploy prod image to dockerhub'
    task prod: %w[git:warn
                  dockerhub:takelbase:project:prod:registry:login
                  rubylint
                  takelscripts
                  ansible:project:prod:from_base:test
                  image:docker:takelbase:project:prod:from_base
                  image:docker:takelbase:project:prod:test
                  git:tag
                  dockerhub:takelbase:project:prod:registry:tag
                  dockerhub:takelbase:project:prod:registry:push]
  end
end
