---
takel_gopass_deb_preinstall_packages:
  - apt-transport-https
  - ca-certificates

takel_gopass_deb_install_packages:
  - gopass

takel_gopass_version: '1.12.8'
takel_gopass_deb: gopass_{{ takel_gopass_version }}_linux_amd64.deb
takel_gopass_tmp: "/tmp/{{ takel_gopass_deb }}"
takel_gopass_url: >-
  https://github.com/gopasspw/gopass/releases/download/v{{
  takel_gopass_version }}/{{ takel_gopass_deb }}

takel_gopass_completion_dir: /etc/bash_completion.d
takel_gopass_bash_completion: >-
  {{ takel_gopass_completion_dir }}/gopass
