---
takel_gopass_deb_preinstall_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg

takel_gopass_deb_install_packages:
  - gopass

takel_gopass_repository_keyring_url: >-
  https://packages.gopass.pw/repos/gopass/gopass-archive-keyring.gpg
takel_gopass_repository_keyring_path: /etc/apt/trusted.gpg.d
takel_gopass_repository_keyring_file: >-
  {{ takel_gopass_repository_keyring_path }}/gopass-archive-keyring.gpg
takel_gopass_repository_filename: gopass.list
takel_gopass_repository_codename: stable
takel_gopass_repository_url: >-
  https://packages.gopass.pw/repos/gopass
takel_gopass_repository_file: >-
  deb
  [arch={{ arch }} signed-by={{ takel_gopass_repository_keyring_file }}]
  {{ takel_gopass_repository_url }}
  {{ takel_gopass_repository_codename }}
  main

takel_gopass_completion_dir: /etc/bash_completion.d
takel_gopass_bash_completion: >-
  {{ takel_gopass_completion_dir }}/gopass

architectures:
  aarch64: arm64
  arm64: arm64
  x86_64: amd64

arch: "{{ architectures[ansible_facts['architecture']] | default('noarch') }}"
