# frozen_string_literal: true

require 'rake'

cmd_vagrantup_takelbase_project_cloud_login = 'vagrant cloud auth login'

cmd_vagrantup_takelbase_project_cloud_publish = 'cd packer && ' \
    'vagrant cloud publish ' \
    '--force ' \
    '--release ' \
    "--description #{@project['vagrantup_project_description']} " \
    "#{@project['vagrantup_project_user']}/#{@project['vagrantup_project_repo']} " \
    "#{@project['version']} " \
    'virtualbox ' \
    'images/vbox/takelbase/project/package.box'

namespace :vagrantup do
  namespace :takelbase do
    namespace :project do
      namespace :cloud do
        desc 'Log in to app.vagrantup.com'
        task :login do
          @commands << cmd_vagrantup_takelbase_project_cloud_login
        end

        desc 'Publish base image at app.vagrantup.com'
        task :publish do
          @commands << cmd_vagrantup_takelbase_project_cloud_publish
        end
      end
    end
  end
end
