---
- name: (install) install packages
  package:
    name: "{{ takel_anarchism_deb_install_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: takel_anarchism_install
