---
- name: (main) include install tasks
  import_tasks: install.yml
  tags:
    - takel
    - takel_nginx
    - takel_nginx

- name: (main) include configure tasks
  import_tasks: configure.yml
  tags:
    - takel
    - takel_nginx
    - takel_nginx_configure
