---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: true
    enabled: true
    masked: false

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: true
    enabled: true
    masked: false
