---
- name: converge
  hosts: molecule-takel-nginx
  gather_facts: false
  pre_tasks:
    - name: attach molecule container to docker network
      docker_container:
        name: "{{ inventory_hostname }}"
        networks:
          - name: "{{ lookup('env','HOSTNAME') }}"
        networks_cli_compatible: false
        privileged: true
      delegate_to: 127.0.0.1

  roles:
    - takel-ssl-self-signed
    - takel-nginx
