---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint molecule/*/*.yml
  flake8
platforms:
  - name: molecule-takel-nginx
    image: takelage/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        takel_ssl_self_signed_common_name: >-
          molecule-takel-nginx
        takel_ssl_self_signed_subject_alt_name: >-
          molecule-takel-nginx.local
        takel_nginx_server_names:
          - molecule-takel-nginx
          - molecule-takel-nginx.local
verifier:
  name: testinfra
  options:
    # p: cacheprovider  # enable cache
    s: true  # capture output
    vvv: true
  additional_files_or_dirs:
    - ../system/test_*.py
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
