# frozen_string_literal: true

cmd_img_build_docker_debian10 = 'docker pull debian:buster-slim && ' \
    'mkdir -p packer/images/docker/debian/buster && ' \
    'cd packer && packer build ' \
    "--var 'base_repo=debian' " \
    "--var 'base_tag=buster-slim' " \
    "--var 'target_user=#{@project['local_user']}' " \
    "--var 'target_repo=#{@project['dockerhub_base_tag']}' " \
    "--var 'target_tag=latest' " \
    'templates/base/docker/debian10/packer.json'

namespace :image do
  namespace :base do
    namespace :docker do
      desc 'Build Debian buster image with packer'
      task :debian10 do
        @commands << cmd_img_build_docker_debian10
      end
    end
  end
end
