---
- name: (bin) create bin directory
  file:
    path: "{{ takel_etherpad_bin }}"
    state: directory
  become_user: etherpad

- name: (bin) copy scripts
  template:
    src: "{{ item }}.j2.sh"
    dest: "{{ takel_etherpad_bin }}/{{ item }}"
    mode: 0755
  become_user: etherpad
  loop:
    - etherpad-admin-password-dice
    - etherpad-admin-password-get
    - etherpad-admin-password-set
    - takelpad

- name: (bin) create symlink to takelpad script
  file:
    src: "{{ takel_etherpad_bin }}/takelpad"
    dest: /usr/local/bin/takelpad
    state: link
