---
- name: (install) install packages
  apt:
    name: "{{ takel_etherpad_deb_install_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: (install) is this the first run?
  stat:
    path: "{{ takel_etherpad_lib }}/.git"
  register: etherpad_lib_git

- name: (install) git fetch etherpad-lite
  command: "git --git-dir={{ takel_etherpad_lib }}/.git --work-tree {{ takel_etherpad_lib }} fetch"
  changed_when: False
  when: etherpad_lib_git.stat.exists
  become_user: etherpad

- name: (install) get the latest git id from origin develop branch
  command: "git --git-dir={{ takel_etherpad_lib }}/.git --work-tree {{ takel_etherpad_lib }} rev-parse origin/develop"
  changed_when: False
  when: etherpad_lib_git.stat.exists
  register: git_rev_parse_origin_master
  become_user: etherpad

- name: (install) get the last but one git id from local develop branch
  command: "git --git-dir={{ takel_etherpad_lib }}/.git --work-tree {{ takel_etherpad_lib }} rev-parse HEAD^"
  changed_when: False
  when: etherpad_lib_git.stat.exists
  register: git_rev_parse_master_up
  become_user: etherpad

- name: (install) git clone etherpad-lite if the local branch differs more than one commit from upstream
  git:
    repo: "{{ takel_etherpad_repo }}"
    dest: "{{ takel_etherpad_lib }}"
  register: git_clone_etherpad_lite
  when: not etherpad_lib_git.stat.exists or (etherpad_lib_git.stat.exists and (git_rev_parse_origin_master.stdout != git_rev_parse_master_up.stdout))
  become_user: etherpad
