# frozen_string_literal: true

require 'rake'

namespace :image do
  namespace :docker do
    namespace :takelbase do
      namespace :project do
        namespace :prod do |env|
          @cmd_image_project.each do |task, command|
            next if %i[from_prod].include? task

            desc 'Build takelbase project image with packer'
            task task do
              @commands << format(
                command,
                project_environment: env.scope.head
              )
            end
          end
        end
      end
    end
  end
end
