---
- name: (casigned) create cert chain
  set_fact:
    cert_chain: |
      {{ takel_ssl_cert }}
      {{ takel_ssl_ca | default('') }}

- name: (casigned) copy cert
  copy:
    dest: "{{ takel_ssl_certs_path }}/{{ takel_ssl_cert_file }}"
    content: "{{ cert_chain }}"
  notify: "{{ takel_ssl_services_handler | default ([]) }}"

- name: (casigned) copy ssl key
  copy:
    dest: "{{ takel_ssl_key_path }}/{{ takel_ssl_key_file }}"
    content: "{{ takel_ssl_key }}"
  notify: "{{ takel_ssl_services_handler | default ([]) }}"
