---
takel_nginx_deb_packages:
  - nginx

takel_nginx_webroot: /var/www/html/
takel_nginx_config_path: /etc/nginx
takel_nginx_server_names:
  - example
  - example.localhost
takel_nginx_site_name: site
takel_nginx_ssl_cert: /etc/ssl/certs/ssl.pem
takel_nginx_ssl_key: /etc/ssl/private/ssl.key
takel_nginx_ssl_session_cache: shared:SSL:10m
takel_nginx_ssl_ciphers:
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-CHACHA20-POLY1305
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES128-GCM-SHA256

takel_nginx_site: |
  server {
    listen 80 default deferred;
    server_name {{ takel_nginx_server_names | join(' ') }};

    try_files $uri/index.html $uri.html $uri
    root {{ takel_nginx_webroot }};
  }

  server {
    listen 443 default deferred;
    server_name {{ takel_nginx_server_names | join(' ') }};
    ssl on;
    ssl_certificate {{ takel_nginx_ssl_cert }};
    ssl_certificate_key {{ takel_nginx_ssl_key }};
    ssl_ciphers {{ takel_nginx_ssl_ciphers | join(':') }};
    ssl_session_cache {{ takel_nginx_ssl_session_cache }};

    try_files $uri/index.html $uri.html $uri
    root {{ takel_nginx_webroot }};
  }
