---
driver:
  name: docker
platforms:
  - name: molecule-takelage-pad-packer
    image: packer_local/takelage-pad:prod
    privileged: false
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../../playbook-project-prod.yml
verifier:
  name: testinfra
  options:
    disable-pytest-warnings: true
    # m: debug
    s: true
    testvars-no-gather-facts: true
    v: true
scenario:
  create_sequence:
    - create
  converge_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - check
    - destroy
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - verify
    - destroy
