---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint playbook*.yml
  flake8
platforms:
  - name: molecule-takelage-pad
    image: takelage/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    groups:
      - private
      - users
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    links:
      group_vars: ../../group_vars
  playbooks:
    converge: ../../playbook-project-prod.yml
verifier:
  name: testinfra
  options:
    disable-pytest-warnings: true
    # m: debug
    s: true
    testvars-no-gather-facts: true
    v: true
  additional_files_or_dirs:
    # integration
    - ../../../roles/*/molecule/default/tests/test_*.py
    # system
    - ../../../roles/*/molecule/default/system/test_*.py
scenario:
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
