---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: molecule-takelage-pad-test-project-${TAKELAGE_PROJECT_ENV:-default}
    image: ${TAKELAGE_PROJECT_BASE_IMAGE:-takelage/takelbase}
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:${TAKELAGE_PAD_PORT_HTTP:-80}:80/tcp
      - 127.0.0.1:${TAKELAGE_PAD_PORT_HTTPS:-443}:443/tcp
    groups:
      - ${TAKELAGE_PROJECT_ENV:-prod}
      - private
      - users
provisioner:
  name: ansible
  playbooks:
    converge: >-
      ../../${TAKELAGE_MOLECULE_CONVERGE_PLAYBOOK:-playbook-project-base.yml}
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: yaml
      bin_ansible_callbacks: true
  inventory:
    links:
      group_vars: ../../group_vars/
verifier:
  name: testinfra
  options:
    # m: debug
    s: true
    v: true
  additional_files_or_dirs:
    # integration
    - ../../../roles/*/molecule/default/tests/test_*.py
    # system
    - ../../../roles/*/molecule/default/system/test_*.py
scenario:
  create_sequence:
    - create
    - prepare
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
