---
- name: (main) include create
  ansible.builtin.import_tasks: create.yml
  when: takel_user_create
  tags:
    - takel
    - takel_user
    - takel_user_create

- name: (main) include bashrc
  ansible.builtin.import_tasks: bashrc.yml
  tags:
    - takel
    - takel_user
    - takel_user_bashrc

- name: (main) include configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - takel
    - takel_user
    - takel_user_configure
