---
- name: (main) include create
  import_tasks: create.yml
  tags:
    - takel
    - takel_user
    - takel_user_create

- name: (main) include configure
  import_tasks: configure.yml
  tags:
    - takel
    - takel_user
    - takel_user_configure
