# frozen_string_literal: true

require 'rake'

namespace :vagrantup do
  namespace :takelbase do
    desc 'Create and deploy base image to vagrantup'
    task project: %w[vagrantup:takelbase:project:cloud:login
                     rubylint
                     image:vbox:takelbase:project:build
                     vagrantup:takelbase:project:cloud:publish]
  end
end
