---
- name: "(users) [{{ takel_mysql_site }}]: create system users"
  include_role:
    name: takel_user
  vars:
    takel_user_name: "{{ user.sys_user }}"
    takel_user_group: "{{ user.sys_group }}"
    takel_user_home: "{{ user.sys_home }}"
    takel_user_shell: >-
      {{ user.sys_shell | default(takel_mysql_default_groups) }}
    takel_user_groups: >-
      {{ user.sys_groups | default(takel_mysql_default_groups) }}
  loop: "{{ takel_mysql_user_my_cnf | default([]) }}"
  loop_control:
    loop_var: user

- name: "(users) [{{ takel_mysql_site }}]: copy user password credentials"
  template:
    src: user_my_cnf.j2
    dest: "{{ item.sys_home }}/.my.cnf"
    owner: "{{ item.sys_user }}"
    group: "{{ item.sys_group }}"
    mode: 0600
  loop: "{{ takel_mysql_user_my_cnf | default([]) }}"
  notify: restart mysql
  no_log: true
