---
- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_root
    - takel_root_install

- name: (main) include configure
  import_tasks: configure.yml
  tags:
    - takel
    - takel_root
    - takel_root_configure
