---
driver:
  name: docker
platforms:
  - name: molecule-takelage-pad-test-image
    image: packer_local/takelage-pad-${TAKELAGE_PROJECT_IMG:-non}
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: systest
    networks:
      - name: systest
  - name: molecule-takelage-pad-test-image-system
    image: takelwerk/takelslim
    command: /usr/bin/tail -f /dev/null
    pre_build_image: true
    networks:
      - name: systest
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: >-
      ../../${TAKELAGE_MOLECULE_CONVERGE_PLAYBOOK:-playbook-site.yml}
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: yaml
      bin_ansible_callbacks: true
  inventory:
    links:
      group_vars: ../../group_vars/
verifier:
  name: testinfra
  options:
    s: true
  additional_files_or_dirs: ${TAKELAGE_MOLECULE_VERIFIER_FILES:-[]}
  env:
    TESTVARS_ROLES_PLAYBOOKS: >-
      ${TAKELAGE_MOLECULE_VERIFIER_PLAYS:-../../playbook-site.yml}
    TESTVARS_ROLES_INCLUDE: takel_user:takel_systemd
scenario:
  create_sequence:
    - create
  converge_sequence:
    - create
    - prepare
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - prepare
    - verify
    - syntax
    - destroy
