---
- name: (main) include services tasks
  import_tasks: services.yml
  tags:
    - takel
    - takel_systemd
    - takel_systemd_services

- name: (main) include tree tasks
  import_tasks: tree.yml
  tags:
    - takel
    - takel_systemd
    - takel_systemd_tree

- name: (main) include env tasks
  import_tasks: env.yml
  tags:
    - takel
    - takel_systemd
    - takel_systemd_env
