---
- name: (services) copy systemd service file
  template:
    src: systemd_template.service.j2
    dest: "/etc/systemd/system/{{ item.name }}.service"
  loop: "{{ takel_systemd_service_list }}"
  register: new_installed_services
  notify:
    - reload daemon
    - enable services

- name: (services) fetch changed services
  set_fact:
    takel_systemd_handler_services_list: >-
       {{ takel_systemd_handler_services_list + [item.item['name']] }}
  loop: "{{ new_installed_services['results'] }}"
  when:
    - item['changed'] is defined
    - item['changed']
