# frozen_string_literal: true

require 'rake'

# rubocop:disable Metrics/BlockLength
namespace :ansible do
  namespace :docker do
    namespace :takelbase do
      namespace :roles do
        desc 'Run molecule tests for all roles skipping errors'
        task :all do
          @commands << @cmd_ansible_docker_takelbase_test_roles_all
        end
        desc 'Run molecule tests for each role failing in case of errors'
        task :each do
          @commands << @cmd_ansible_docker_takelbase_test_roles_each
        end
        Dir.glob('ansible/roles/*/molecule').each do |role_path|
          role = role_path.match(%r{roles/(?<role_name>.*)/molecule})
          namespace role[:role_name] do
            @list_ansible_docker_takelbase_role.each do |command|
              desc "Run molecule #{command} for #{role[:role_name]}"
              task command do
                @commands << format(
                  @cmd_ansible_docker_takelbase_role,
                  command: command,
                  role_path: role_path.split('/molecule')[0]
                )
              end
            end
          end
        end
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength
