---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint molecule/*/*.yml
  flake8
platforms:
  - name: molecule-takelage-dev-local-${TAKELAGE_PROJECT_ENV:-prod}
    image: packer_local/mapapp:${TAKELAGE_PROJECT_ENV:-prod}
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:${TAKELAGE_PAD_PORT_HTTP:-80}:80/tcp
      - 127.0.0.1:${TAKELAGE_PAD_PORT_HTTPS:-443}:443/tcp
    groups:
      - ${TAKELAGE_PROJECT_ENV:-prod}
      - users
      - molecule
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    links:
      group_vars: ../../group_vars/
verifier:
  name: testinfra
  options:
    # p: cacheprovider  # enable cache
    s: true  # capture output
    v: true
scenario:
  create_sequence:
    - create
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
