---
- name: (install) install packages
  apt:
    name: "{{ takel_ufw_deb_install_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: (install) copy /etc/default/ufw
  template:
    src: templates/default_ufw.j2
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: 0644
