---
- name: "(install) [{{ takel_mysql_site }}] install packages"
  apt:
    name: "{{ takel_mysql_deb_install_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "(install) [{{ takel_mysql_site }}] create include directory"
  file:
    path: /etc/mysql/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "(install) [{{ takel_mysql_site }}] delete mysql log files in /var/log"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/log/mysql.err
    - /var/log/mysql.log

- name: "(install) [{{ takel_mysql_site }}] start and enable mysql"
  service:
    name: mysql
    state: started
    enabled: true
