---
- name: "(loop_users) {{ user.sys_user }}: create system group"
  group:
    name: "{{ user.sys_group }}"
  notify: restart mysql
  when: user.sys_shell is defined and user.sys_shell
  tags:
    - takel
    - takel_mysql
    - takel_mysql_loop_user

- name: "(loop_users) {{ user.sys_user }}: create system user"
  user:
    name: "{{ user.sys_user }}"
    group: "{{ user.sys_group }}"
    home: "{{ user.sys_home }}"
    shell: "{{ user.sys_shell }}"
  when: user.sys_shell is defined and user.sys_shell
  tags:
    - takel
    - takel_mysql
    - takel_mysql_loop_user
