---
- name: (playbook-project-prod) create project prod
  hosts: all
  become: true
  roles:
    - takel-base
    - takel-anarchism
    - takel-ufw
    - takel-unattended-upgrades
    - takel-mysql
    - takel-nodejs
    - takel-ssl
    - takel-nginx
    - takel-etherpad
    - takel-takelpad
    - takel-cleanup
