---
- name: (main) include upgrade
  ansible.builtin.import_tasks: upgrade.yml
  tags:
    - takel
    - takel_base
    - takel_base_upgrade

- name: (main) include install
  ansible.builtin.import_tasks: install.yml
  tags:
    - takel
    - takel_base
    - takel_base_install

- name: (main) include configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - takel
    - takel_base
    - takel_base_configure
