# frozen_string_literal: true

cmd_image_vbox_takelbase_project_build = \
  'rm -fr packer/images/vbox/takelbase/project && ' \
  'cd packer && ' \
  'packer build ' \
  "--var 'ansible_playbook=site.yml' " \
  'templates/vbox/takelbase/project/main.pkr.hcl'

namespace :image do
  namespace :vbox do
    namespace :takelbase do
      namespace :project do
        desc 'Build virtualbox project image'
        task :build do
          @commands << cmd_image_vbox_takelbase_project_build
        end
      end
    end
  end
end
