# frozen_string_literal: true

require 'rake'

namespace :dockerhub do
  desc 'Create and deploy prod image to dockerhub'
  task prod: %w[git:warn
                rubylint
                dockerhub:prod:registry:login
                test:project
                image:prod:build
                image:prod:test
                git:tag
                dockerhub:prod:registry:tag
                dockerhub:prod:registry:push]
end
