---
- name: (version) create version file
  copy:
    content: "{{ takel_takelpad_version }}\n"
    dest: "{{ takel_takelpad_version_file }}"
    owner: root
    group: root
    mode: 0644
  when: takel_takelpad_version is defined
