---
name: Build and deploy project vbox

on:
  schedule: # run daily at 1 pm CET
    - cron: '0 2 * * *'
  workflow_dispatch:  # allow manual trigger

jobs:
  build-and-deploy-project-vbox:
    runs-on: macos-10.15
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install ansible
        run: brew install ansible

      - name: Install tau
        run: gem install takeltau

      - name: Build vagrant box
        run: rake vboxes:project:build

      - name: Push vagrant box
        run: rake vagrantup:project:push
