---
name: Build and deploy project vbox to vagrantup

on:
  push:  # trigger on git push
  workflow_dispatch:  # allow manual trigger

jobs:
  build-and-deploy-project-vbox:
    runs-on: macos-10.15
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install ansible
        run: brew install ansible

      - name: Install tau
        run: gem install takeltau

      - name: Build vagrant box
        run: rake vboxes:project:build

      - name: Push vagrant box
        run: ATLAS_TOKEN=${{ secrets.ATLAS_TOKEN }} rake vagrantup:project:push
