---
name: takelpad virtualbox

on:
  workflow_dispatch:

jobs:
  takelpad-virtualbox:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install ansible
        run: brew install ansible

      - name: Install tau
        run: gem install takeltau

      - name: Build vagrant box
        run: rake vboxes:project:build

      - name: Push vagrant box
        run: ATLAS_TOKEN=${{ secrets.ATLAS_TOKEN }} rake vagrantup:virtualbox:project:push
