---
name: test roles

on:
  schedule:  # run daily at 2 pm CET
    - cron: '0 4 * * *'
  workflow_dispatch:  # allow manual trigger

jobs:
  test-roles:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - name: Install tau
        run: gem install takeltau

      - name: Configure tau
        run: |
          echo "docker_entrypoint_options: --no-git --no-gopass --no-gpg --no-ssh" >> $HOME/.takelage.yml
          echo "docker_repo: takelbuild" >> $HOME/.takelage.yml
          echo "docker_tag: latest-amd64" >> $HOME/.takelage.yml
          cat $HOME/.takelage.yml

      - name: Pull takelage image
        run: tau update

      - name: Read mutagen version
        run: |
          MUTAGEN=$(docker inspect --format '{{ index .Config.Labels "mutagen" }}' takelwerk/takelbuild:latest-amd64)
          echo "MUTAGEN=$MUTAGEN" >> "$GITHUB_ENV"

      - name: Install mutagen
        run: |
          MUTAGEN_FILE=https://github.com/mutagen-io/mutagen/releases/download/v${{ env.MUTAGEN }}/mutagen_linux_amd64_v${{ env.MUTAGEN }}.tar.gz
          wget --header="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -O /tmp/mutagen.tar.gz $MUTAGEN_FILE
          sudo tar xvfz /tmp/mutagen.tar.gz -C /usr/local/bin
          mutagen daemon start

      - name: Start an instance of takelage
        run: tau docker container daemon

      - name: Test roles
        run: tau docker container command "ANSIBLE_ROLES_PATH=/project/ansible/roles rake ansible:roles:each"
